/*
 * This file is generated by jOOQ.
*/
package br.com.lnable.domain;


import br.com.lnable.domain.tables.Pessoa;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PocJooq extends SchemaImpl {

    private static final long serialVersionUID = -1382739198;

    /**
     * The reference instance of <code>poc-jooq</code>
     */
    public static final PocJooq POC_JOOQ = new PocJooq();

    /**
     * The table <code>poc-jooq.Pessoa</code>.
     */
    public final Pessoa PESSOA = br.com.lnable.domain.tables.Pessoa.PESSOA;

    /**
     * No further instances allowed
     */
    private PocJooq() {
        super("poc-jooq", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Pessoa.PESSOA);
    }
}
