/*
 * This file is generated by jOOQ.
*/
package br.com.lnable.domain;


import br.com.lnable.domain.tables.Pessoa;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in poc-jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>poc-jooq.Pessoa</code>.
     */
    public static final Pessoa PESSOA = br.com.lnable.domain.tables.Pessoa.PESSOA;
}
