/*
 * This file is generated by jOOQ.
*/
package br.com.lnable.domain.tables.records;


import br.com.lnable.domain.tables.Pessoa;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PessoaRecord extends UpdatableRecordImpl<PessoaRecord> implements Record5<Integer, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1054606851;

    /**
     * Setter for <code>poc-jooq.Pessoa.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>poc-jooq.Pessoa.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>poc-jooq.Pessoa.nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>poc-jooq.Pessoa.nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>poc-jooq.Pessoa.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>poc-jooq.Pessoa.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>poc-jooq.Pessoa.telefone</code>.
     */
    public void setTelefone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>poc-jooq.Pessoa.telefone</code>.
     */
    public String getTelefone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>poc-jooq.Pessoa.dt-criacao</code>.
     */
    public void setDtCriacao(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>poc-jooq.Pessoa.dt-criacao</code>.
     */
    public Timestamp getDtCriacao() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Pessoa.PESSOA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Pessoa.PESSOA.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Pessoa.PESSOA.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Pessoa.PESSOA.TELEFONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Pessoa.PESSOA.DT_CRIACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDtCriacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value2(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value4(String value) {
        setTelefone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value5(Timestamp value) {
        setDtCriacao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PessoaRecord
     */
    public PessoaRecord() {
        super(Pessoa.PESSOA);
    }

    /**
     * Create a detached, initialised PessoaRecord
     */
    public PessoaRecord(Integer id, String nome, String email, String telefone, Timestamp dtCriacao) {
        super(Pessoa.PESSOA);

        set(0, id);
        set(1, nome);
        set(2, email);
        set(3, telefone);
        set(4, dtCriacao);
    }
}
