/*
 * This file is generated by jOOQ.
*/
package br.com.lnable.jooq.domain;


import br.com.lnable.jooq.domain.tables.Pessoa;
import br.com.lnable.jooq.domain.tables.records.PessoaRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>poc-jooq</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PessoaRecord, Integer> IDENTITY_PESSOA = Identities0.IDENTITY_PESSOA;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PessoaRecord> KEY_PESSOA_PRIMARY = UniqueKeys0.KEY_PESSOA_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<PessoaRecord, Integer> IDENTITY_PESSOA = createIdentity(Pessoa.PESSOA, Pessoa.PESSOA.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<PessoaRecord> KEY_PESSOA_PRIMARY = createUniqueKey(Pessoa.PESSOA, "KEY_Pessoa_PRIMARY", Pessoa.PESSOA.ID);
    }
}
