/*
 * This file is generated by jOOQ.
*/
package br.com.lnable.domain.tables;


import br.com.lnable.domain.Keys;
import br.com.lnable.domain.PocJooq;
import br.com.lnable.domain.tables.records.PessoaRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pessoa extends TableImpl<PessoaRecord> {

    private static final long serialVersionUID = -895073481;

    /**
     * The reference instance of <code>poc-jooq.Pessoa</code>
     */
    public static final Pessoa PESSOA = new Pessoa();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PessoaRecord> getRecordType() {
        return PessoaRecord.class;
    }

    /**
     * The column <code>poc-jooq.Pessoa.id</code>.
     */
    public final TableField<PessoaRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>poc-jooq.Pessoa.nome</code>.
     */
    public final TableField<PessoaRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>poc-jooq.Pessoa.email</code>.
     */
    public final TableField<PessoaRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>poc-jooq.Pessoa.telefone</code>.
     */
    public final TableField<PessoaRecord, String> TELEFONE = createField("telefone", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

    /**
     * The column <code>poc-jooq.Pessoa.dt-criacao</code>.
     */
    public final TableField<PessoaRecord, Timestamp> DT_CRIACAO = createField("dt-criacao", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>poc-jooq.Pessoa</code> table reference
     */
    public Pessoa() {
        this("Pessoa", null);
    }

    /**
     * Create an aliased <code>poc-jooq.Pessoa</code> table reference
     */
    public Pessoa(String alias) {
        this(alias, PESSOA);
    }

    private Pessoa(String alias, Table<PessoaRecord> aliased) {
        this(alias, aliased, null);
    }

    private Pessoa(String alias, Table<PessoaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PocJooq.POC_JOOQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PessoaRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PESSOA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PessoaRecord> getPrimaryKey() {
        return Keys.KEY_PESSOA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PessoaRecord>> getKeys() {
        return Arrays.<UniqueKey<PessoaRecord>>asList(Keys.KEY_PESSOA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Pessoa as(String alias) {
        return new Pessoa(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pessoa rename(String name) {
        return new Pessoa(name, null);
    }
}
